//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAME.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public float CrashDetector_Threshold_Ax {
            get {
                return ((float)(this["CrashDetector_Threshold_Ax"]));
            }
            set {
                this["CrashDetector_Threshold_Ax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public float CrashDetector_Threshold_Ay {
            get {
                return ((float)(this["CrashDetector_Threshold_Ay"]));
            }
            set {
                this["CrashDetector_Threshold_Ay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float CrashDetector_Threshold_Az {
            get {
                return ((float)(this["CrashDetector_Threshold_Az"]));
            }
            set {
                this["CrashDetector_Threshold_Az"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public float CrashDetector_Threshold_Wx {
            get {
                return ((float)(this["CrashDetector_Threshold_Wx"]));
            }
            set {
                this["CrashDetector_Threshold_Wx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float CrashDetector_Threshold_Wy {
            get {
                return ((float)(this["CrashDetector_Threshold_Wy"]));
            }
            set {
                this["CrashDetector_Threshold_Wy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float CrashDetector_Threshold_Wz {
            get {
                return ((float)(this["CrashDetector_Threshold_Wz"]));
            }
            set {
                this["CrashDetector_Threshold_Wz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PositionOffsetCorrection_DeltaX {
            get {
                return ((float)(this["PositionOffsetCorrection_DeltaX"]));
            }
            set {
                this["PositionOffsetCorrection_DeltaX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PositionOffsetCorrection_DeltaY {
            get {
                return ((float)(this["PositionOffsetCorrection_DeltaY"]));
            }
            set {
                this["PositionOffsetCorrection_DeltaY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PositionOffsetCorrection_DeltaZ {
            get {
                return ((float)(this["PositionOffsetCorrection_DeltaZ"]));
            }
            set {
                this["PositionOffsetCorrection_DeltaZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PositionOffsetCorrection_IsActive {
            get {
                return ((bool)(this["PositionOffsetCorrection_IsActive"]));
            }
            set {
                this["PositionOffsetCorrection_IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float AlphaCompensation_AlphaZero {
            get {
                return ((float)(this["AlphaCompensation_AlphaZero"]));
            }
            set {
                this["AlphaCompensation_AlphaZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float AlphaCompensation_CompensationPercentage {
            get {
                return ((float)(this["AlphaCompensation_CompensationPercentage"]));
            }
            set {
                this["AlphaCompensation_CompensationPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float AlphaCompensation_FadeIn_Start {
            get {
                return ((float)(this["AlphaCompensation_FadeIn_Start"]));
            }
            set {
                this["AlphaCompensation_FadeIn_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float AlphaCompensation_FadeIn_Done {
            get {
                return ((float)(this["AlphaCompensation_FadeIn_Done"]));
            }
            set {
                this["AlphaCompensation_FadeIn_Done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlphaCompensation_IsActive {
            get {
                return ((bool)(this["AlphaCompensation_IsActive"]));
            }
            set {
                this["AlphaCompensation_IsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Filtervariable_Wx_HP {
            get {
                return ((float)(this["Filtervariable_Wx_HP"]));
            }
            set {
                this["Filtervariable_Wx_HP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Filtervariable_Wx_HP_LP {
            get {
                return ((float)(this["Filtervariable_Wx_HP_LP"]));
            }
            set {
                this["Filtervariable_Wx_HP_LP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float FilterVariable_Wy_HP {
            get {
                return ((float)(this["FilterVariable_Wy_HP"]));
            }
            set {
                this["FilterVariable_Wy_HP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Filtervariable_Wy_HP_LP {
            get {
                return ((float)(this["Filtervariable_Wy_HP_LP"]));
            }
            set {
                this["Filtervariable_Wy_HP_LP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Filtervariable_Wz_HP {
            get {
                return ((float)(this["Filtervariable_Wz_HP"]));
            }
            set {
                this["Filtervariable_Wz_HP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Filtervariable_Wz_HP_LP {
            get {
                return ((float)(this["Filtervariable_Wz_HP_LP"]));
            }
            set {
                this["Filtervariable_Wz_HP_LP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Filtervariable_Ax_HP {
            get {
                return ((float)(this["Filtervariable_Ax_HP"]));
            }
            set {
                this["Filtervariable_Ax_HP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Filtervariable_Ax_HP_LP2 {
            get {
                return ((float)(this["Filtervariable_Ax_HP_LP2"]));
            }
            set {
                this["Filtervariable_Ax_HP_LP2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Filtervariable_Ay_HP {
            get {
                return ((float)(this["Filtervariable_Ay_HP"]));
            }
            set {
                this["Filtervariable_Ay_HP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Filtervariable_Ay_HP_LP2 {
            get {
                return ((float)(this["Filtervariable_Ay_HP_LP2"]));
            }
            set {
                this["Filtervariable_Ay_HP_LP2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Filtervariable_Az_HP {
            get {
                return ((float)(this["Filtervariable_Az_HP"]));
            }
            set {
                this["Filtervariable_Az_HP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Filtervariable_Az_HP_LP2 {
            get {
                return ((float)(this["Filtervariable_Az_HP_LP2"]));
            }
            set {
                this["Filtervariable_Az_HP_LP2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Filtervariable_Ax_LP3 {
            get {
                return ((float)(this["Filtervariable_Ax_LP3"]));
            }
            set {
                this["Filtervariable_Ax_LP3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Filtervariable_Az_LP3 {
            get {
                return ((float)(this["Filtervariable_Az_LP3"]));
            }
            set {
                this["Filtervariable_Az_LP3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string CompressionMethod_Roll_HFC {
            get {
                return ((string)(this["CompressionMethod_Roll_HFC"]));
            }
            set {
                this["CompressionMethod_Roll_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string CompressionMethod_Yaw_HFC {
            get {
                return ((string)(this["CompressionMethod_Yaw_HFC"]));
            }
            set {
                this["CompressionMethod_Yaw_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string CompressionMethod_Pitch_HFC {
            get {
                return ((string)(this["CompressionMethod_Pitch_HFC"]));
            }
            set {
                this["CompressionMethod_Pitch_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string CompressionMethod_Surge_HFC {
            get {
                return ((string)(this["CompressionMethod_Surge_HFC"]));
            }
            set {
                this["CompressionMethod_Surge_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string CompressionMethod_Heave_HFC {
            get {
                return ((string)(this["CompressionMethod_Heave_HFC"]));
            }
            set {
                this["CompressionMethod_Heave_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string CompressionMethod_Sway_HFC {
            get {
                return ((string)(this["CompressionMethod_Sway_HFC"]));
            }
            set {
                this["CompressionMethod_Sway_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string CompressionMethod_Pitch_LFC {
            get {
                return ((string)(this["CompressionMethod_Pitch_LFC"]));
            }
            set {
                this["CompressionMethod_Pitch_LFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string CompressionMethod_Roll_LFC {
            get {
                return ((string)(this["CompressionMethod_Roll_LFC"]));
            }
            set {
                this["CompressionMethod_Roll_LFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float CompressionParameter_Roll_HFC {
            get {
                return ((float)(this["CompressionParameter_Roll_HFC"]));
            }
            set {
                this["CompressionParameter_Roll_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float CompressionParameter_Yaw_HFC {
            get {
                return ((float)(this["CompressionParameter_Yaw_HFC"]));
            }
            set {
                this["CompressionParameter_Yaw_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float CompressionParameter_Pitch_HFC {
            get {
                return ((float)(this["CompressionParameter_Pitch_HFC"]));
            }
            set {
                this["CompressionParameter_Pitch_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float CompressionParameter_Surge_HFC {
            get {
                return ((float)(this["CompressionParameter_Surge_HFC"]));
            }
            set {
                this["CompressionParameter_Surge_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float CompressionParameter_Heave_HFC {
            get {
                return ((float)(this["CompressionParameter_Heave_HFC"]));
            }
            set {
                this["CompressionParameter_Heave_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float CompressionParameter_Sway_HFC {
            get {
                return ((float)(this["CompressionParameter_Sway_HFC"]));
            }
            set {
                this["CompressionParameter_Sway_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float CompressionParameter_Pitch_LFC {
            get {
                return ((float)(this["CompressionParameter_Pitch_LFC"]));
            }
            set {
                this["CompressionParameter_Pitch_LFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float CompressionParameter_Roll_LFC {
            get {
                return ((float)(this["CompressionParameter_Roll_LFC"]));
            }
            set {
                this["CompressionParameter_Roll_LFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float CompressionLimit_Roll_HFC {
            get {
                return ((float)(this["CompressionLimit_Roll_HFC"]));
            }
            set {
                this["CompressionLimit_Roll_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float CompressionLimit_Yaw_HFC {
            get {
                return ((float)(this["CompressionLimit_Yaw_HFC"]));
            }
            set {
                this["CompressionLimit_Yaw_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float CompressionLimit_Pitch_HFC {
            get {
                return ((float)(this["CompressionLimit_Pitch_HFC"]));
            }
            set {
                this["CompressionLimit_Pitch_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float CompressionLimit_Surge_HFC {
            get {
                return ((float)(this["CompressionLimit_Surge_HFC"]));
            }
            set {
                this["CompressionLimit_Surge_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float CompressionLimit_Heave_HFC {
            get {
                return ((float)(this["CompressionLimit_Heave_HFC"]));
            }
            set {
                this["CompressionLimit_Heave_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float CompressionLimit_Sway_HFC {
            get {
                return ((float)(this["CompressionLimit_Sway_HFC"]));
            }
            set {
                this["CompressionLimit_Sway_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float CompressionLimit_Pitch_LFC {
            get {
                return ((float)(this["CompressionLimit_Pitch_LFC"]));
            }
            set {
                this["CompressionLimit_Pitch_LFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float CompressionLimit_Roll_LFC {
            get {
                return ((float)(this["CompressionLimit_Roll_LFC"]));
            }
            set {
                this["CompressionLimit_Roll_LFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float Scaler_Gain_RollHFC {
            get {
                return ((float)(this["Scaler_Gain_RollHFC"]));
            }
            set {
                this["Scaler_Gain_RollHFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float Scaler_Gain_YawHFC {
            get {
                return ((float)(this["Scaler_Gain_YawHFC"]));
            }
            set {
                this["Scaler_Gain_YawHFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float Scaler_Gain_PitchHFC {
            get {
                return ((float)(this["Scaler_Gain_PitchHFC"]));
            }
            set {
                this["Scaler_Gain_PitchHFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float Scaler_Gain_HeaveHFC {
            get {
                return ((float)(this["Scaler_Gain_HeaveHFC"]));
            }
            set {
                this["Scaler_Gain_HeaveHFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float Scaler_Gain_SwayHFC {
            get {
                return ((float)(this["Scaler_Gain_SwayHFC"]));
            }
            set {
                this["Scaler_Gain_SwayHFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float Scaler_Gain_RollLFC {
            get {
                return ((float)(this["Scaler_Gain_RollLFC"]));
            }
            set {
                this["Scaler_Gain_RollLFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float Scaler_Gain_PitchLFC {
            get {
                return ((float)(this["Scaler_Gain_PitchLFC"]));
            }
            set {
                this["Scaler_Gain_PitchLFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float Scaler_Gain_SurgeHFC {
            get {
                return ((float)(this["Scaler_Gain_SurgeHFC"]));
            }
            set {
                this["Scaler_Gain_SurgeHFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Zeromaker_Zero_RollHFC {
            get {
                return ((bool)(this["Zeromaker_Zero_RollHFC"]));
            }
            set {
                this["Zeromaker_Zero_RollHFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Zeromaker_Zero_YawHFC {
            get {
                return ((bool)(this["Zeromaker_Zero_YawHFC"]));
            }
            set {
                this["Zeromaker_Zero_YawHFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Zeromaker_Zero_PitchHFC {
            get {
                return ((bool)(this["Zeromaker_Zero_PitchHFC"]));
            }
            set {
                this["Zeromaker_Zero_PitchHFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Zeromaker_Zero_SurgeHFC {
            get {
                return ((bool)(this["Zeromaker_Zero_SurgeHFC"]));
            }
            set {
                this["Zeromaker_Zero_SurgeHFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Zeromaker_Zero_PitchLFC {
            get {
                return ((bool)(this["Zeromaker_Zero_PitchLFC"]));
            }
            set {
                this["Zeromaker_Zero_PitchLFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Zeromaker_Zero_HeaveHFC {
            get {
                return ((bool)(this["Zeromaker_Zero_HeaveHFC"]));
            }
            set {
                this["Zeromaker_Zero_HeaveHFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Zeromaker_Zero_SwayHFC {
            get {
                return ((bool)(this["Zeromaker_Zero_SwayHFC"]));
            }
            set {
                this["Zeromaker_Zero_SwayHFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Zeromaker_Zero_RollLFC {
            get {
                return ((bool)(this["Zeromaker_Zero_RollLFC"]));
            }
            set {
                this["Zeromaker_Zero_RollLFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("717")]
        public float Integrator_OffsetPark {
            get {
                return ((float)(this["Integrator_OffsetPark"]));
            }
            set {
                this["Integrator_OffsetPark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1021")]
        public float Integrator_OffsetPause {
            get {
                return ((float)(this["Integrator_OffsetPause"]));
            }
            set {
                this["Integrator_OffsetPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float Integrator_OffsetCoR {
            get {
                return ((float)(this["Integrator_OffsetCoR"]));
            }
            set {
                this["Integrator_OffsetCoR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1136")]
        public float Dist_A_Upper {
            get {
                return ((float)(this["Dist_A_Upper"]));
            }
            set {
                this["Dist_A_Upper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("178")]
        public float Dist_B_Upper {
            get {
                return ((float)(this["Dist_B_Upper"]));
            }
            set {
                this["Dist_B_Upper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110")]
        public float Dist_A_Lower {
            get {
                return ((float)(this["Dist_A_Lower"]));
            }
            set {
                this["Dist_A_Lower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1391")]
        public float Dist_B_Lower {
            get {
                return ((float)(this["Dist_B_Lower"]));
            }
            set {
                this["Dist_B_Lower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public float Window_RigConfig_Position_X {
            get {
                return ((float)(this["Window_RigConfig_Position_X"]));
            }
            set {
                this["Window_RigConfig_Position_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public float Window_RigConfig_Position_Y {
            get {
                return ((float)(this["Window_RigConfig_Position_Y"]));
            }
            set {
                this["Window_RigConfig_Position_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("520")]
        public float ActuatorSystem_Stroke {
            get {
                return ((float)(this["ActuatorSystem_Stroke"]));
            }
            set {
                this["ActuatorSystem_Stroke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("970")]
        public float ActuatorSystem_MinLength {
            get {
                return ((float)(this["ActuatorSystem_MinLength"]));
            }
            set {
                this["ActuatorSystem_MinLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public float Window_RawData_Position_X {
            get {
                return ((float)(this["Window_RawData_Position_X"]));
            }
            set {
                this["Window_RawData_Position_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public float Window_RawData_Position_Y {
            get {
                return ((float)(this["Window_RawData_Position_Y"]));
            }
            set {
                this["Window_RawData_Position_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public float Window_SceneView_Position_X {
            get {
                return ((float)(this["Window_SceneView_Position_X"]));
            }
            set {
                this["Window_SceneView_Position_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public float Window_SceneView_Position_Y {
            get {
                return ((float)(this["Window_SceneView_Position_Y"]));
            }
            set {
                this["Window_SceneView_Position_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_RawData_IsOpen {
            get {
                return ((bool)(this["Window_RawData_IsOpen"]));
            }
            set {
                this["Window_RawData_IsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_SceneView_IsOpen {
            get {
                return ((bool)(this["Window_SceneView_IsOpen"]));
            }
            set {
                this["Window_SceneView_IsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_RigConfig_IsOpen {
            get {
                return ((bool)(this["Window_RigConfig_IsOpen"]));
            }
            set {
                this["Window_RigConfig_IsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_CrashDetector_IsOpen {
            get {
                return ((bool)(this["Window_CrashDetector_IsOpen"]));
            }
            set {
                this["Window_CrashDetector_IsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public float Window_CrashDetector_Position_X {
            get {
                return ((float)(this["Window_CrashDetector_Position_X"]));
            }
            set {
                this["Window_CrashDetector_Position_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public float Window_CrashDetector_Position_Y {
            get {
                return ((float)(this["Window_CrashDetector_Position_Y"]));
            }
            set {
                this["Window_CrashDetector_Position_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public float Window_PositionCorrection_Position_X {
            get {
                return ((float)(this["Window_PositionCorrection_Position_X"]));
            }
            set {
                this["Window_PositionCorrection_Position_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public float Window_PositionCorrection_Position_Y {
            get {
                return ((float)(this["Window_PositionCorrection_Position_Y"]));
            }
            set {
                this["Window_PositionCorrection_Position_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_PositionCorrection_IsOpen {
            get {
                return ((bool)(this["Window_PositionCorrection_IsOpen"]));
            }
            set {
                this["Window_PositionCorrection_IsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_AlphaCompensation_IsOpen {
            get {
                return ((bool)(this["Window_AlphaCompensation_IsOpen"]));
            }
            set {
                this["Window_AlphaCompensation_IsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float Window_AlphaCompensation_Position_X {
            get {
                return ((float)(this["Window_AlphaCompensation_Position_X"]));
            }
            set {
                this["Window_AlphaCompensation_Position_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float Window_AlphaCompensation_Position_Y {
            get {
                return ((float)(this["Window_AlphaCompensation_Position_Y"]));
            }
            set {
                this["Window_AlphaCompensation_Position_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_Filters_IsOpen {
            get {
                return ((bool)(this["Window_Filters_IsOpen"]));
            }
            set {
                this["Window_Filters_IsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public float Window_Filters_Position_X {
            get {
                return ((float)(this["Window_Filters_Position_X"]));
            }
            set {
                this["Window_Filters_Position_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public float Window_Filters_Position_Y {
            get {
                return ((float)(this["Window_Filters_Position_Y"]));
            }
            set {
                this["Window_Filters_Position_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_Graphs_IsOpen {
            get {
                return ((bool)(this["Window_Graphs_IsOpen"]));
            }
            set {
                this["Window_Graphs_IsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public float Window_Graphs_Position_X {
            get {
                return ((float)(this["Window_Graphs_Position_X"]));
            }
            set {
                this["Window_Graphs_Position_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public float Window_Graphs_Position_Y {
            get {
                return ((float)(this["Window_Graphs_Position_Y"]));
            }
            set {
                this["Window_Graphs_Position_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_DOFs_IsOpen {
            get {
                return ((bool)(this["Window_DOFs_IsOpen"]));
            }
            set {
                this["Window_DOFs_IsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float Window_DOFs_Position_X {
            get {
                return ((float)(this["Window_DOFs_Position_X"]));
            }
            set {
                this["Window_DOFs_Position_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float Window_DOFs_Position_Y {
            get {
                return ((float)(this["Window_DOFs_Position_Y"]));
            }
            set {
                this["Window_DOFs_Position_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_MotionControl_IsOpen {
            get {
                return ((bool)(this["Window_MotionControl_IsOpen"]));
            }
            set {
                this["Window_MotionControl_IsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public float Window_MotionControl_Position_X {
            get {
                return ((float)(this["Window_MotionControl_Position_X"]));
            }
            set {
                this["Window_MotionControl_Position_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public float Window_MotionControl_Position_Y {
            get {
                return ((float)(this["Window_MotionControl_Position_Y"]));
            }
            set {
                this["Window_MotionControl_Position_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Window_OutputAASD_Position_X {
            get {
                return ((float)(this["Window_OutputAASD_Position_X"]));
            }
            set {
                this["Window_OutputAASD_Position_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Window_OutputAASD_Position_Y {
            get {
                return ((float)(this["Window_OutputAASD_Position_Y"]));
            }
            set {
                this["Window_OutputAASD_Position_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_OutputAASD_IsOpen {
            get {
                return ((bool)(this["Window_OutputAASD_IsOpen"]));
            }
            set {
                this["Window_OutputAASD_IsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AASD_Talker_LastUsed_ComPort {
            get {
                return ((string)(this["AASD_Talker_LastUsed_ComPort"]));
            }
            set {
                this["AASD_Talker_LastUsed_ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_SourceSelect_IsOpen {
            get {
                return ((bool)(this["Window_SourceSelect_IsOpen"]));
            }
            set {
                this["Window_SourceSelect_IsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float Window_SourceSelect_Position_X {
            get {
                return ((float)(this["Window_SourceSelect_Position_X"]));
            }
            set {
                this["Window_SourceSelect_Position_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float Window_SourceSelect_Position_Y {
            get {
                return ((float)(this["Window_SourceSelect_Position_Y"]));
            }
            set {
                this["Window_SourceSelect_Position_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31090")]
        public int Server_Port_UDP {
            get {
                return ((int)(this["Server_Port_UDP"]));
            }
            set {
                this["Server_Port_UDP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.806,0,0,0,0,nil")]
        public string Getter_DefaulDataString {
            get {
                return ((string)(this["Getter_DefaulDataString"]));
            }
            set {
                this["Getter_DefaulDataString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Processing_Framerate {
            get {
                return ((int)(this["Processing_Framerate"]));
            }
            set {
                this["Processing_Framerate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001")]
        public float Actuator_TriggerZone {
            get {
                return ((float)(this["Actuator_TriggerZone"]));
            }
            set {
                this["Actuator_TriggerZone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Motion4Sim")]
        public string AASD_Talker_LastUsed_HardwareController {
            get {
                return ((string)(this["AASD_Talker_LastUsed_HardwareController"]));
            }
            set {
                this["AASD_Talker_LastUsed_HardwareController"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Saved Games\\YAME Motion Engine\\Exporters")]
        public string Patcher_ExportersFolder {
            get {
                return ((string)(this["Patcher_ExportersFolder"]));
            }
            set {
                this["Patcher_ExportersFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\FS2020_MotionExporter.exe")]
        public string Patcher_FS2020_Exporter_exe {
            get {
                return ((string)(this["Patcher_FS2020_Exporter_exe"]));
            }
            set {
                this["Patcher_FS2020_Exporter_exe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppData\\Local\\Packages\\Microsoft.FlightSimulator_8wekyb3d8bbwe\\LocalCache")]
        public string Patcher_FS2020_STORE_Folder {
            get {
                return ((string)(this["Patcher_FS2020_STORE_Folder"]));
            }
            set {
                this["Patcher_FS2020_STORE_Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppData\\Roaming\\Microsoft Flight Simulator")]
        public string Patcher_FS2020_STEAM_Folder {
            get {
                return ((string)(this["Patcher_FS2020_STEAM_Folder"]));
            }
            set {
                this["Patcher_FS2020_STEAM_Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nil")]
        public string LoaderSaver_ProfilePath {
            get {
                return ((string)(this["LoaderSaver_ProfilePath"]));
            }
            set {
                this["LoaderSaver_ProfilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Scripts\\Hooks\\YAME_Export_Hook.lua")]
        public string Patcher_DCS_Script {
            get {
                return ((string)(this["Patcher_DCS_Script"]));
            }
            set {
                this["Patcher_DCS_Script"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\XPlane_Motion_Exporter")]
        public string Patcher_Xplane_Exporter {
            get {
                return ((string)(this["Patcher_Xplane_Exporter"]));
            }
            set {
                this["Patcher_Xplane_Exporter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float DOF_Override_Range_Roll_HFC {
            get {
                return ((float)(this["DOF_Override_Range_Roll_HFC"]));
            }
            set {
                this["DOF_Override_Range_Roll_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float DOF_Override_Range_Yaw_HFC {
            get {
                return ((float)(this["DOF_Override_Range_Yaw_HFC"]));
            }
            set {
                this["DOF_Override_Range_Yaw_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float DOF_Override_Range_Pitch_HFC {
            get {
                return ((float)(this["DOF_Override_Range_Pitch_HFC"]));
            }
            set {
                this["DOF_Override_Range_Pitch_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public float DOF_Override_Range_Surge_HFC {
            get {
                return ((float)(this["DOF_Override_Range_Surge_HFC"]));
            }
            set {
                this["DOF_Override_Range_Surge_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public float DOF_Override_Range_Heave_HFC {
            get {
                return ((float)(this["DOF_Override_Range_Heave_HFC"]));
            }
            set {
                this["DOF_Override_Range_Heave_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public float DOF_Override_Range_Sway_HFC {
            get {
                return ((float)(this["DOF_Override_Range_Sway_HFC"]));
            }
            set {
                this["DOF_Override_Range_Sway_HFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float DOF_Override_Range_Pitch_LFC {
            get {
                return ((float)(this["DOF_Override_Range_Pitch_LFC"]));
            }
            set {
                this["DOF_Override_Range_Pitch_LFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float DOF_Override_Range_Roll_LFC {
            get {
                return ((float)(this["DOF_Override_Range_Roll_LFC"]));
            }
            set {
                this["DOF_Override_Range_Roll_LFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123")]
        public float Window_ActuatorOverride_Position_X {
            get {
                return ((float)(this["Window_ActuatorOverride_Position_X"]));
            }
            set {
                this["Window_ActuatorOverride_Position_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("456")]
        public float Window_ActuatorOverride_Position_Y {
            get {
                return ((float)(this["Window_ActuatorOverride_Position_Y"]));
            }
            set {
                this["Window_ActuatorOverride_Position_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_ActuatorOverride_IsOpen {
            get {
                return ((bool)(this["Window_ActuatorOverride_IsOpen"]));
            }
            set {
                this["Window_ActuatorOverride_IsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float Window_OutputODrive_Position_X {
            get {
                return ((float)(this["Window_OutputODrive_Position_X"]));
            }
            set {
                this["Window_OutputODrive_Position_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float Window_OutputODrive_Position_Y {
            get {
                return ((float)(this["Window_OutputODrive_Position_Y"]));
            }
            set {
                this["Window_OutputODrive_Position_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_OutputODrive_IsOpen {
            get {
                return ((bool)(this["Window_OutputODrive_IsOpen"]));
            }
            set {
                this["Window_OutputODrive_IsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ODriveTalker_LastUsedComPort_1 {
            get {
                return ((string)(this["ODriveTalker_LastUsedComPort_1"]));
            }
            set {
                this["ODriveTalker_LastUsedComPort_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ODriveTalker_LastUsedComPort_2 {
            get {
                return ((string)(this["ODriveTalker_LastUsedComPort_2"]));
            }
            set {
                this["ODriveTalker_LastUsedComPort_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ODriveTalker_LastUsedComPort_3 {
            get {
                return ((string)(this["ODriveTalker_LastUsedComPort_3"]));
            }
            set {
                this["ODriveTalker_LastUsedComPort_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ODriveSystem_Lead {
            get {
                return ((int)(this["ODriveSystem_Lead"]));
            }
            set {
                this["ODriveSystem_Lead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p 0 [Act1][newline]p 1 [Act2]")]
        public string ODriveSystem_FormatString_1 {
            get {
                return ((string)(this["ODriveSystem_FormatString_1"]));
            }
            set {
                this["ODriveSystem_FormatString_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p 0 [Act3][newline]p 1 [Act4]")]
        public string ODriveSystem_FormatString_2 {
            get {
                return ((string)(this["ODriveSystem_FormatString_2"]));
            }
            set {
                this["ODriveSystem_FormatString_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p 0 [Act5][newline]p 1 [Act6]")]
        public string ODriveSystem_FormatString_3 {
            get {
                return ((string)(this["ODriveSystem_FormatString_3"]));
            }
            set {
                this["ODriveSystem_FormatString_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Invert_Wx {
            get {
                return ((bool)(this["Invert_Wx"]));
            }
            set {
                this["Invert_Wx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Invert_Wy {
            get {
                return ((bool)(this["Invert_Wy"]));
            }
            set {
                this["Invert_Wy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Invert_Wz {
            get {
                return ((bool)(this["Invert_Wz"]));
            }
            set {
                this["Invert_Wz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Invert_Ax {
            get {
                return ((bool)(this["Invert_Ax"]));
            }
            set {
                this["Invert_Ax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Invert_Ay {
            get {
                return ((bool)(this["Invert_Ay"]));
            }
            set {
                this["Invert_Ay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Invert_Az {
            get {
                return ((bool)(this["Invert_Az"]));
            }
            set {
                this["Invert_Az"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SnappyDragger_SnapDistance {
            get {
                return ((int)(this["SnappyDragger_SnapDistance"]));
            }
            set {
                this["SnappyDragger_SnapDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Getter_Timeout {
            get {
                return ((int)(this["Getter_Timeout"]));
            }
            set {
                this["Getter_Timeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string Getter_MotionSource {
            get {
                return ((string)(this["Getter_MotionSource"]));
            }
            set {
                this["Getter_MotionSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\iRacing_MotionExporter.exe")]
        public string Patcher_iRacing_Exporter_exe {
            get {
                return ((string)(this["Patcher_iRacing_Exporter_exe"]));
            }
            set {
                this["Patcher_iRacing_Exporter_exe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Saved Games\\YAME Motion Engine\\Config\\YAME.cfg")]
        public string Automator_ConfigFilePath {
            get {
                return ((string)(this["Automator_ConfigFilePath"]));
            }
            set {
                this["Automator_ConfigFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Automator_ShowAboutWindowOnStartup {
            get {
                return ((bool)(this["Automator_ShowAboutWindowOnStartup"]));
            }
            set {
                this["Automator_ShowAboutWindowOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Automator_ForceHotRigWarningSilent {
            get {
                return ((bool)(this["Automator_ForceHotRigWarningSilent"]));
            }
            set {
                this["Automator_ForceHotRigWarningSilent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Automator_AutoCrashRecovery {
            get {
                return ((bool)(this["Automator_AutoCrashRecovery"]));
            }
            set {
                this["Automator_AutoCrashRecovery"] = value;
            }
        }
    }
}
